### PR TITLE
MassMatrix corrected

### PR DESCRIPTION
**Pull request by Ergus**
Code implemented inside the matrix.py file.
test_massmatrix added to the test folder.
Notebook modified to perform the tests and mover to the application folder.
The history about the root file was not removed, not necessary.

### CODE REVIEW

**Comment by luca-heltai** [comment]
There is no need to create another pull request. You stubbornly avoid reading documentation, and even here, you did not rebase. Until you rebase to master, I cannot merge.

**Comment by Ergus** [comment]
I come from subversion, so I just created a new branch with a clean
history as you wish. the rebase was made there and everything looks
clean there. thats why I made a new request from there.
I didnt knew that a rebase after a pull reguest will include the new
changes. if the pull is made later. As branch are exactly the same
than commits in git, I cloned an old commit as branch and then applied
the patches with the rebase. But with different hashes I cannot reuse
the same pull request.
Did you finally accepted this changes or not?
yes: may I add the other matrix (derivatives ones)
no: tell me what to do for to success.
Regards Jimmy.

2015-01-07 10:54 GMT+01:00, Luca Heltai <notifications@github.com>:

**Comment by luca-heltai** [comment]
You did a merge. Not a rebase. The graph here:

download

clearly shows that you did a merge from luca-heltai/ePICURE/master to your newly created branch. The documentation I asked you to read states clearly:

When you think your contribution is ready (a contribution is usually one single feature with one test) do the following:

rebase interactively (-i switch) your changes onto the master branch of the remote heltai, after updating your local branches:

  # Get all changes from all remote repositories
  git checkout test
  git fetch --all
  git rebase -i heltai/master

the above command will pop up an editor in which you will be allowed to squash all your commits into a couple, more significant, commits (which means **do it**, don't leave 6 commits, if there are 3 changed files...). Push your changes by forcing the push (you have just changed history, so this will be allowed only if you force your changes)

  git push -f origin test


You could have done this with the old branch you had created for the pull request. Now you can do it with this one (the `test` branch).

**Comment by luca-heltai** [comment]
I forgot to mention... since you merged, the above will fail miserably....

You should undo the merge commits first. I'll do this on a new branch, and I'll show you how to do it. GIT is part of your MHPC training... and you should be very well familiar with it... 

;-)

**Comment by luca-heltai** [comment]
This is what I did to clean up:

~~~ bash
git co b9902583df772aa348054d7ab1faf1aeecc1bd30 -b rebase-jimmy
git cherry-pick a932894884cc9bb8cd0045b51e6585da86d68aa5
git cherry-pick dc0cd99001f52d5d084093ab74da48c23ae2ec65
git cherry-pick be3aa03298e360be10d799b163e895b7ba23c173
git cherry-pick ffea566477bb8761705836f26961283b79fa8f97
git rebase -i origin/master
~~~

Resolving all the conflicts along the way...

**Pull request closed without merging**
